load_dataset_parameters:
  dataset_location: dataset
  datasets_to_load:
    - resale-flat-prices-based-on-registration-date-from-jan-2017-onwards
    - resale-flat-prices-based-on-registration-date-from-jan-2015-to-dec-2016


cleanup_parameters:
  include_features:
    - month
    - town
    - flat_type
    - storey_range
    - floor_area_sqm
    - flat_model
    - remaining_lease
    - resale_price
  
  # remaining_lease has 2 format which are 'YY years XX months' or 'XX' years
  # will focus on years instead
  morph_feature_type:
    remaining_lease: int64 # mixed of string and int type


# Categorical count vizualization
# visualization only includes indicated here
categorical_count_visualization_parameters:
  - town
  - flat_type
  - storey_range
  - flat_model

# TODO check if this still need
numerical_and_categorical_heatmap_parameters:
  features_to_exclude:
    - 

numerical_vs_categorical_eda_visualization_parameters:
  # resale_price: town
  resale_price: flat_type
  # resale_price: storey_range
  resale_price: flat_model
  remaining_lease: town
  remaining_lease: flat_model
  floor_area_sqm: flat_type

# time_feature has to be datetime64[ns] only
# observe_feature has to be numerical only
# groupby_feature has be categorical only
# supported observation_type are sum, mean, median, min, and max
time_series_parameters:
  - time_feature: month
    observe_feature: resale_price
    groupby_features:
      - town
    # need to add color feature
    observation_types: 
      min: red
      mean: blue
      max: green
  
  # floor_area_sqm observation must be based on the flat_type
  # - observe_value: floor_area_sqm
  #   groupby: 
  #     - town
  #     - flat_type
  #   observation_type: 
  #   - min
  #   - mean
  #   - max



linear_regression_parameters:

  - response: resale_price
    predictors: 
      - floor_area_sqm
      - remaining_lease


  # - response: resale_price
  #   predictors: 
  #     - flat_type
  #     - flat_model

  # - response: remaining_lease
  #   predictors:
  #     - town
  #     - flat_model 
  
  # - response: floor_area_sqm
  #   predictors:
  #     - flat_type